### PR TITLE
PostGIS database setup

### LINKED ISSUE #18: OSM Database Import
Use imposm3 and PostGIS to create a reproducable database container from OSM planet files.
The whole import process should be automated.

The tm2source project can then connect to the database and generate the vector tiles.

### PR DESCRIPTION
**Pull request by lukasmartinelli**
Resolves #18.
This should allow to setup a docker based infrastructure in a short time.
PostGIS container and the imposm3 container are separated from each other.

This will probably not be replicated many times but in theory it is probably one of the easiest
way to get started with osm custom vector tiles.
One should test the entire process and the documentation.

### CODE REVIEW

**Comment by manuelroth** [comment]
- Documentation is very clear and understandable
- If the postgres user and osm user are the same, an sql error gets thrown "role does already exist". But this shouldn't be a problem. 
- Are you sure that the default postgres user and password is osm?- Because in the docu of the official postgres container it says postgres.

**Comment by manuelroth** [comment]
- Import Container cant connect to database container because the database requires the password to be md5 hashed. 
```
FATAL:  password authentication failed for user "osm"
DETAIL:  Connection matched pg_hba.conf line 95: "host all all 0.0.0.0/0 md5"
```

**Comment by lukasmartinelli** [comment]
> Import Container cant connect to database container because the database requires the password to be md5 hashed.

If I follow the instructions on a clean machine I should be able to replicate this?
Is this the `osm` user with a password differrent than `osm`?

**Comment by manuelroth** [comment]
Yes, you should be able to replicate this. Exactly I used osm as user and password.

**Comment by lukasmartinelli** [comment]
Got another weird error on a small 500MB machine that I could not replicate.

`/docker-entrypoint.sh: line 70: cannot create temp file for here-document: Cannot allocate memory`

We need to find out the system requirements. When importing I got an out of memory with imposm3.
However I had no problems connecting with imposm3 o the postgresql container.

**Comment by sfkeller** [comment]
Getting out-of-memory is a typical problem when converting ways to lines, since all nodes (which are referred to from the ways and contain the coordinates) need to be loaded or at least queried.

In osm2pgsql we initially had similar problems before setting "slim mode":
http://wiki.openstreetmap.org/wiki/Osm2pgsql#Slim_mode

**Comment by lukasmartinelli** [comment]
> Getting out-of-memory is a typical problem when converting ways to lines, since all nodes (which are referred to from the ways and contain the coordinates) need to be loaded or at least queried.
> 
> In osm2pgsql we initially had similar problems before setting "slim mode":
> http://wiki.openstreetmap.org/wiki/Osm2pgsql#Slim_mode

Many thanks for this experience. There are some config options http://imposm.org/docs/imposm3/latest/tutorial.html#config-file that could be tweaked to get more conservative memory usage.

- [ ] Measure memory usage of imposm3 and check the limits

**Comment by lukasmartinelli** [comment]
Not able to replicate the md5 error so far.

**Log**:

```
docker run --name postgis \
    -v /data/pgdata:/var/lib/postgresql/data \
    -e POSTGRES_USER=postgres \
    -e POSTGRES_PASSWORD=postgres \
    -e OSM_DB=osm \
    -e OSM_USER=osm \
    -e OSM_PASSWORD=osm \
    -d osm2vectortiles/postgis
```

Output:

```
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data ... ok
creating subdirectories ... ok
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting dynamic shared memory implementation ... posix
creating configuration files ... ok
creating template1 database in /var/lib/postgresql/data/base/1 ... ok
initializing pg_authid ... ok
initializing dependencies ... ok
creating system views ... ok
loading system objects' descriptions ... ok
creating collations ... ok
creating conversions ... ok
creating dictionaries ... ok
setting privileges on built-in objects ... ok
creating information schema ... ok
loading PL/pgSQL server-side language ... ok
vacuuming database template1 ... ok
copying template1 to template0 ... ok
copying template1 to postgres ... ok
syncing data to disk ... ok

WARNING: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.

Success. You can now start the database server using:

    postgres -D /var/lib/postgresql/data
or
    pg_ctl -D /var/lib/postgresql/data -l logfile start

waiting for server to start....LOG:  database system was shut down at 2015-09-26 18:15:52 UTC
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
 done
server started
ALTER ROLE


/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/10_postgis.sh
CREATE DATABASE
UPDATE 1
Loading PostGIS into template_postgis
CREATE EXTENSION
CREATE EXTENSION
CREATE EXTENSION
CREATE EXTENSION
CREATE EXTENSION
Loading PostGIS into postgres
CREATE EXTENSION
CREATE EXTENSION
CREATE EXTENSION
CREATE EXTENSION
CREATE EXTENSION
Loading vt-util functions into template_postgis
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION

/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/20_osm.sh
Creating database osm with owner osm
CREATE ROLE
CREATE DATABASE

LOG:  received fast shutdown request
LOG:  aborting any active transactions
LOG:  autovacuum launcher shutting down
LOG:  shutting down
waiting for server to shut down....LOG:  database system is shut down
 done
server stopped

PostgreSQL init process complete; ready for start up.

LOG:  database system was shut down at 2015-09-26 18:16:00 UTC
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
```

Then in the directory `/data/import`:

```
wget https://s3.amazonaws.com/metro-extracts.mapzen.com/zurich_switzerland.osm.pbf
```

Then import:

```
docker run --rm --name imposm \
    -v /data/import:/data/import \
    -v /data/cache:/data/cache \
    --link postgis:db \
    -e OSM_DB=osm \
    -e OSM_USER=osm \
    -e OSM_PASSWORD=osm \
    osm2vectortiles/imposm3
```

Output:

```
[Sep 26 18:18:18] [INFO] [reader] reading /data/import/zurich_switzerland.osm.pbf with data till 2015-09-26 00:26:02 +0000 UTC
[Sep 26 18:18:31] [INFO] [   12s] C: 7409000/s (2434364) N:   70800/s (31384) W:       0/s (384353) R:      0/s (1091)
[Sep 26 18:18:31] [INFO] Reading OSM data took: 12.538288601s
[Sep 26 18:18:31] [INFO] Imposm took: 12.53966314s
[Sep 26 18:18:31] [INFO] [mapping] warn: zorder type is deprecated and will be removed. See enumerate type.
[Sep 26 18:18:31] [INFO] [mapping] warn: zorder type is deprecated and will be removed. See enumerate type.
[Sep 26 18:18:33] [INFO] [mapping] warn: zorder type is deprecated and will be removed. See enumerate type.
[Sep 26 18:18:35] [INFO] [mapping] warn: zorder type is deprecated and will be removed. See enumerate type.
[Sep 26 18:19:16] [INFO] [mapping] warn: zorder type is deprecated and will be removed. See enumerate type.
[Sep 26 18:19:20] [INFO] Writing OSM data took: 48.892667108s
[Sep 26 18:19:20] [INFO] [   48s] C:       0/s (0) N:    8700/s (31384) W:    9500/s (384353) R:    350/s (1091)
[Sep 26 18:19:20] [INFO] [PostGIS] Generalizing osm_waterareas into osm_waterareas_gen1 took: 62.961692ms
[Sep 26 18:19:20] [INFO] [PostGIS] Generalizing osm_roads into osm_roads_gen1 took: 773.614761ms
[Sep 26 18:19:21] [INFO] [PostGIS] Generalizing osm_waterways into osm_waterways_gen1 took: 122.466352ms
[Sep 26 18:19:21] [INFO] [PostGIS] Generalizing osm_landusages into osm_landusages_gen1 took: 921.142615ms
[Sep 26 18:19:21] [INFO] [PostGIS] Generalizing osm_waterareas into osm_waterareas_gen0 took: 8.594081ms
[Sep 26 18:19:22] [INFO] [PostGIS] Generalizing osm_roads into osm_roads_gen0 took: 161.60764ms
[Sep 26 18:19:22] [INFO] [PostGIS] Generalizing osm_waterways into osm_waterways_gen0 took: 58.593286ms
[Sep 26 18:19:22] [INFO] [PostGIS] Generalizing osm_landusages into osm_landusages_gen0 took: 133.107723ms
[Sep 26 18:19:22] [INFO] [PostGIS] Creating generalized tables took: 2.242825964s
[Sep 26 18:19:22] [INFO] [PostGIS] Creating OSM id index on osm_transport_points took: 6.371737ms
[Sep 26 18:19:22] [INFO] [PostGIS] Creating geometry index on osm_transport_points took: 52.424753ms
[Sep 26 18:19:22] [INFO] [PostGIS] Creating OSM id index on osm_places took: 5.781669ms
[Sep 26 18:19:22] [INFO] [PostGIS] Creating geometry index on osm_places took: 9.688599ms
[Sep 26 18:19:22] [INFO] [PostGIS] Creating OSM id index on osm_waterways took: 15.38781ms
[Sep 26 18:19:22] [INFO] [PostGIS] Creating geometry index on osm_waterways took: 56.781927ms
[Sep 26 18:19:22] [INFO] [PostGIS] Creating OSM id index on osm_landusages took: 32.811096ms
[Sep 26 18:19:23] [INFO] [PostGIS] Creating geometry index on osm_landusages took: 495.701173ms
[Sep 26 18:19:23] [INFO] [PostGIS] Creating OSM id index on osm_admin took: 5.745659ms
[Sep 26 18:19:23] [INFO] [PostGIS] Creating geometry index on osm_admin took: 4.158402ms
[Sep 26 18:19:23] [INFO] [PostGIS] Creating OSM id index on osm_motorways took: 6.378245ms
[Sep 26 18:19:23] [INFO] [PostGIS] Creating geometry index on osm_motorways took: 13.160455ms
[Sep 26 18:19:23] [INFO] [PostGIS] Creating OSM id index on osm_housenumbers took: 29.319599ms
[Sep 26 18:19:23] [INFO] [PostGIS] Creating geometry index on osm_housenumbers took: 372.938085ms
[Sep 26 18:19:23] [INFO] [PostGIS] Creating OSM id index on osm_roads took: 134.406989ms
[Sep 26 18:19:25] [INFO] [PostGIS] Creating geometry index on osm_roads took: 2.290931655s
[Sep 26 18:19:25] [INFO] [PostGIS] Creating OSM id index on osm_mainroads took: 10.845542ms
[Sep 26 18:19:25] [INFO] [PostGIS] Creating geometry index on osm_mainroads took: 56.78444ms
[Sep 26 18:19:26] [INFO] [PostGIS] Creating OSM id index on osm_minorroads took: 88.481339ms
[Sep 26 18:19:27] [INFO] [PostGIS] Creating geometry index on osm_minorroads took: 1.170438295s
[Sep 26 18:19:27] [INFO] [PostGIS] Creating OSM id index on osm_barrierways took: 5.810747ms
[Sep 26 18:19:27] [INFO] [PostGIS] Creating geometry index on osm_barrierways took: 21.418123ms
[Sep 26 18:19:27] [INFO] [PostGIS] Creating OSM id index on osm_barrierpoints took: 4.274905ms
[Sep 26 18:19:27] [INFO] [PostGIS] Creating geometry index on osm_barrierpoints took: 13.985625ms
[Sep 26 18:19:27] [INFO] [PostGIS] Creating OSM id index on osm_aeroways took: 2.192094ms
[Sep 26 18:19:27] [INFO] [PostGIS] Creating geometry index on osm_aeroways took: 1.147361ms
[Sep 26 18:19:27] [INFO] [PostGIS] Creating OSM id index on osm_buildings took: 178.68782ms
[Sep 26 18:19:33] [INFO] [PostGIS] Creating geometry index on osm_buildings took: 5.682785822s
[Sep 26 18:19:33] [INFO] [PostGIS] Creating OSM id index on osm_transport_areas took: 57.384106ms
[Sep 26 18:19:33] [INFO] [PostGIS] Creating geometry index on osm_transport_areas took: 2.514972ms
[Sep 26 18:19:33] [INFO] [PostGIS] Creating OSM id index on osm_housenumbers_interpolated took: 4.627406ms
[Sep 26 18:19:33] [INFO] [PostGIS] Creating geometry index on osm_housenumbers_interpolated took: 1.273504ms
[Sep 26 18:19:33] [INFO] [PostGIS] Creating OSM id index on osm_waterareas took: 4.459777ms
[Sep 26 18:19:33] [INFO] [PostGIS] Creating geometry index on osm_waterareas took: 22.591076ms
[Sep 26 18:19:33] [INFO] [PostGIS] Creating OSM id index on osm_amenities took: 3.392727ms
[Sep 26 18:19:33] [INFO] [PostGIS] Creating geometry index on osm_amenities took: 7.013615ms
[Sep 26 18:19:33] [INFO] [PostGIS] Creating OSM id index on osm_waterareas_gen1 took: 3.044772ms
[Sep 26 18:19:33] [INFO] [PostGIS] Creating geometry index on osm_waterareas_gen1 took: 1.264709ms
[Sep 26 18:19:33] [INFO] [PostGIS] Creating OSM id index on osm_waterareas_gen0 took: 2.058706ms
[Sep 26 18:19:33] [INFO] [PostGIS] Creating geometry index on osm_waterareas_gen0 took: 1.067293ms
[Sep 26 18:19:33] [INFO] [PostGIS] Creating OSM id index on osm_roads_gen0 took: 31.5211ms
[Sep 26 18:19:33] [INFO] [PostGIS] Creating geometry index on osm_roads_gen0 took: 255.974161ms
[Sep 26 18:19:33] [INFO] [PostGIS] Creating OSM id index on osm_roads_gen1 took: 19.462774ms
[Sep 26 18:19:33] [INFO] [PostGIS] Creating geometry index on osm_roads_gen1 took: 243.612577ms
[Sep 26 18:19:33] [INFO] [PostGIS] Creating OSM id index on osm_waterways_gen0 took: 10.548183ms
[Sep 26 18:19:33] [INFO] [PostGIS] Creating geometry index on osm_waterways_gen0 took: 40.664384ms
[Sep 26 18:19:33] [INFO] [PostGIS] Creating OSM id index on osm_waterways_gen1 took: 6.142841ms
[Sep 26 18:19:33] [INFO] [PostGIS] Creating geometry index on osm_waterways_gen1 took: 69.235131ms
[Sep 26 18:19:33] [INFO] [PostGIS] Creating OSM id index on osm_landusages_gen1 took: 10.272743ms
[Sep 26 18:19:33] [INFO] [PostGIS] Creating geometry index on osm_landusages_gen1 took: 32.21894ms
[Sep 26 18:19:33] [INFO] [PostGIS] Creating OSM id index on osm_landusages_gen0 took: 3.228397ms
[Sep 26 18:19:33] [INFO] [PostGIS] Creating geometry index on osm_landusages_gen0 took: 3.008936ms
[Sep 26 18:19:33] [INFO] [PostGIS] Creating geometry indices took: 11.607891144s
[Sep 26 18:19:33] [INFO] Importing OSM data took: 1m2.743559952s
[Sep 26 18:19:33] [INFO] Imposm took: 1m2.743873809s
```

**Comment by manuelroth** [comment]
Created a bug for the mounting issue #22

**Pull request merged**
