### PR TITLE
Feature/gatling

### PR DESCRIPTION
**Pull request by manuelroth**
Added instructions to run gatling with provided scenarios

### CODE REVIEW

**Comment by lukasmartinelli** [comment]
Yeah nice work!

I am not sure whether we want to check in the results into the Git repo (2k files is quite something).
But we definitely need to store the results somewhere.

**Comment by manuelroth** [comment]
- The test results at first glance may look not very impressive. With 50 concurrent users, 50% of the request take longer than 1200 ms. But we have to keep in mind, that this tileserver consciously uses no caching and runs on a very small machine. 
- I'm probably going to test it on a bigger machine for comparison.
- Thanks @lukasmartinelli I'll have a look there load-tester, maybe we can integrate it. 
- @klokan loader.io looks nice, I'll try if the free plan is suitable for our usecase.

**Comment by manuelroth** [comment]
@lukasmartinelli yes, you are right, its too much data. I wonder, if there is an option for less verbose results. The global result output at the end of the test contains already all interesting information. I need to check on that.

**Comment by lukasmartinelli** [comment]
Results are removed :+1:

**Pull request merged**
