### PR TITLE
First tileserver implementation based on tessera

### PR DESCRIPTION
**Pull request by lukasmartinelli**
A minimal viable implementation of a vector tileserver #5.
This is not a fully featured tileserver but was the fastest way to get started.

It uses tessera (which uses tilelive Mapnik) https://github.com/mojodna/tessera 
Tessera allows serving raster tiles from various sources (including `.tm2` projects). It also allows you to simply put a `mbtiles` source directly into the `project.yml` style config.

The docker container executes a script to replace the source with the mbtiles file found in the mounted volume.

My wish is to start from here and iterate from there (because now we have a minimal tileserver that is already working). In the next version one might think about using renderd on top of tileserver-php and compare the performance. Or perhaps just do nginx-caching in front of tessera.

Raster tiles are only generated on the fly at the moment. This allows to immediately surf the web map after the mbtiles and styles have been put into the volume.

Prerendering all raster tiles might take a long time but should be implemented in the next iteration.

### CODE REVIEW

**Comment by manuelroth** [comment]
- [ ] Handle case when a directory with the tm2 project is mounted to the /data volume, but the directory still does not contain a tm2 project
- Is it a convention that the mbtiles must have the same name as the tm2 project?- One could also have a mbtiles file called switzerland.mbtiles and a tm2 project called osm-bright.tm2. The mbtiles file is not always related to the style. 
- In a future iteration we could give the possibility of declaring the name of the mbtiles file or just take any file with the .mbtiles file extension. 
- What do you think about this?- I'm not quite sure what the best solution is. I think high usability should be the goal.

**Comment by lukasmartinelli** [comment]
> Is it a convention that the mbtiles must have the same name as the tm2 project?- One could also have a mbtiles file called switzerland.mbtiles and a tm2 project called osm-bright.tm2. The mbtiles file is not always related to the style.

The docker container only supports one single project at the moment. Therefore it would be possible to link any `mbtiles` file with any `tm2` project by default.
But in the future one might support multiple projects (like tileserver-php) does and then this convention makes a bit more sense.

> In a future iteration we could give the possibility of declaring the name of the mbtiles file or just take any file with the .mbtiles file extension.

Alot of people like explicit configuration better indeed.
Something like:

```
MBTILES_FILE=/data/countries.mbtiles
TM2_PROJECT_FILE=/data/countries.tm2
```

This might be a bit confusing because one has to take the path of the `/data` volume.

**Comment by lukasmartinelli** [comment]
Another thing about tessera. It does not serve `pbf` files directly to clients like e.g. Mapbox Studio or Mapbox GL. This should be added in the future as well.

**Comment by manuelroth** [comment]
Created issues for ideas and added them as enhancements in milestone final. -> #23 #24

**Pull request merged**
